WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 800
VIRTUAL_HEIGHT = 450

SHIP_SPEED = 450

METEOR_SPEED_MAX = 151

METEOR_SPEED = math.random(150, METEOR_SPEED_MAX)

-- for determining the pos of player
PLAYERSHIP_X = 0 
PLAYERSHIP_Y = 0

-- show player health or not
SHOW_HEALTH = false